In [8]:
import numpy as np

In [9]:
# Calculate profit/loss from revenue and expenses
revenue = np.array([[180,200,220],[24,36,40],[12,18,20]])
expenses = np.array([[80,90,100],[10,16,20],[8,10,10]])

In [10]:
profit = revenue - expenses
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [11]:
# Calculate total sales from units and price per unit using matrix multiplication
price_per_unit = np.array([1000,400,1200])
units = np.array([[30,40,50],[5,10,15],[2,5,7]])

In [12]:
price_per_unit*units

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

In [13]:
np.dot(price_per_unit,units)


array([34400, 50000, 64400])

In [14]:
# Below is some indian companies revenues in US dollars. Using numpy can you convert this into Indian rupees? 
# 1 USD = 75 INR

In [18]:
revenue_dollars = np.array([[180,200,220],[24,36,40],[12,18,20]])
revenue_inr = np.dot(75 , revenue_dollars)
revenue_inr

array([[13500, 15000, 16500],
       [ 1800,  2700,  3000],
       [  900,  1350,  1500]])

In [15]:
# Divine flowers is a flower shop that sells different type of flowers. 
# Below is the table showing how many flowers of each type they sold in different months. 
# Also given are the prices of one flower each. Using this find out their total sales in every month.


In [28]:
units_sold = np.array([[50,60,25],[10,13,5],[40,70,52]])
price_per_unit = np.array([20,30,15])
total_sales_amount = np.dot(price_per_unit,units_sold)
total_sales_amount


array([1900, 2640, 1430])